//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestASBConnection.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class ApplicationsSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static ApplicationsSetting defaultInstance = ((ApplicationsSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ApplicationsSetting())));
        
        public static ApplicationsSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=dsm09.jmadsm.dk;Initial Catalog=JMA_base;Persist Security Info=True;U" +
            "ser ID=res_base;Password=89JMAdsm89JMAdsm;TrustServerCertificate=True;")]
        public string SqlConnection {
            get {
                return ((string)(this["SqlConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://event-proxy-service.jma-dev.net/api/v1/events/")]
        public string ApiEndPoint {
            get {
                return ((string)(this["ApiEndPoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3|qa4au1XriJ5wXJRRQi5kTfhJ4OUJfVuBCczVZQW23095ae57")]
        public string BearerToken {
            get {
                return ((string)(this["BearerToken"]));
            }
        }
    }
}
